apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "meta.name" $ }}
  labels: {{ include "meta.labels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key | upper }}: {{ $val | quote}}
  {{- end }}
