apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "meta.name" $ }}
  labels: {{ include "meta.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end }}
stringData:
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key | upper }}: {{ $val | quote }}
  {{- end }}
