---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: gunicorn
  labels: {{ include "meta.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: gunicorn
      port: 8000
      protocol: TCP
      targetPort: gunicorn
{{- if .Values.monitoring.enabled }}
    - name: exporter
      port: 9102
      protocol: TCP
      targetPort: exporter
{{- end }}
  selector:
    app: {{ include "meta.name" $ }}-gunicorn
