{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "meta.name" $ }}-statsd
  namespace: {{ .Release.Namespace }}
  labels: {{ include "meta.labels" $ | nindent 4 }}
data:
  statsd.conf: |
    mappings:
    - match: example-api.gunicorn.request.status.*
      help: "http response code"
      name: "data_api_http_response_code"
      labels:
        status: "$1"
        job: "data_api_gunicorn_response_code"
{{- end }}
